// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5EVNjPJWTDX2BEowuH3C7et3kNpxnYAM',
    appId: '1:483219299233:web:b1c850e97543af5b5e09e0',
    messagingSenderId: '483219299233',
    projectId: 'auth-demo-c035c',
    authDomain: 'auth-demo-c035c.firebaseapp.com',
    databaseURL: 'https://auth-demo-c035c-default-rtdb.firebaseio.com',
    storageBucket: 'auth-demo-c035c.appspot.com',
    measurementId: 'G-QKNT0TWYRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfyMECwRlMrjxUdLhHhg6IgkVPt3REUtw',
    appId: '1:483219299233:android:b122af012b17ed505e09e0',
    messagingSenderId: '483219299233',
    projectId: 'auth-demo-c035c',
    databaseURL: 'https://auth-demo-c035c-default-rtdb.firebaseio.com',
    storageBucket: 'auth-demo-c035c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHwLVUF6ppYv9SIIiBsP3WIeKgn-tFwKg',
    appId: '1:483219299233:ios:72527d1b9437570a5e09e0',
    messagingSenderId: '483219299233',
    projectId: 'auth-demo-c035c',
    databaseURL: 'https://auth-demo-c035c-default-rtdb.firebaseio.com',
    storageBucket: 'auth-demo-c035c.appspot.com',
    iosClientId: '483219299233-rsqvc876q4ssadb1ps5ub1gkq6d8puvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.skinlesion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHwLVUF6ppYv9SIIiBsP3WIeKgn-tFwKg',
    appId: '1:483219299233:ios:72527d1b9437570a5e09e0',
    messagingSenderId: '483219299233',
    projectId: 'auth-demo-c035c',
    databaseURL: 'https://auth-demo-c035c-default-rtdb.firebaseio.com',
    storageBucket: 'auth-demo-c035c.appspot.com',
    iosClientId: '483219299233-rsqvc876q4ssadb1ps5ub1gkq6d8puvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.skinlesion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5EVNjPJWTDX2BEowuH3C7et3kNpxnYAM',
    appId: '1:483219299233:web:904e2e0535e7bbe15e09e0',
    messagingSenderId: '483219299233',
    projectId: 'auth-demo-c035c',
    authDomain: 'auth-demo-c035c.firebaseapp.com',
    databaseURL: 'https://auth-demo-c035c-default-rtdb.firebaseio.com',
    storageBucket: 'auth-demo-c035c.appspot.com',
    measurementId: 'G-F37SQKF3B6',
  );
}
